// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, public_member_api_docs
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWPcUT9EGTk9tfETqZxVIx_ZPs1m3mmz4',
    appId: '1:657756630904:android:f7264638bf4a7c73b0228d',
    messagingSenderId: '657756630904',
    projectId: 'wallet-connect-df3e4',
    storageBucket: 'wallet-connect-df3e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_XRDPewyWlYjfzURxw_RjDkTo77EHb4M',
    appId: '1:657756630904:ios:219aa26263a2bf7db0228d',
    messagingSenderId: '657756630904',
    projectId: 'wallet-connect-df3e4',
    storageBucket: 'wallet-connect-df3e4.appspot.com',
    iosClientId:
        '657756630904-kqbf5qoudq97elf3571dh0go6ikier8f.apps.googleusercontent.com',
    iosBundleId: 'com.hextools.walletConnect',
  );
}
